menu:
- {name: 'Publications', url: '/publications'}
- {name: 'Courses', url: '/courses'}

courses:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
# - {icon: 'github', link: 'https://github.com/MKutay'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'instagram', link: 'https://instagram.com/mkutayboz'}
# - {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}